baseURL: https://blog.admarus.net/
languageCode: en-us
title: Admarus Blog
theme: "PaperMod"

params:
  env: production
  description: "Blog for Admarus: A peer-to-peer search engine for IPFS"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    favicon: "https://admarus.net/assets/logo.png"

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/mubelotix"
    - name: github
      url: "https://github.com/mubelotix/admarus"
    - name: linkedin
      url: "https://www.linkedin.com/in/simon-g748572/"
  
  editPost:
    URL: "https://github.com/Mubelotix/admarus-blog/content"
    Text: "Suggest Changes"
    appendFilePath: true

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: github
      name: Github
      url: https://github.com/Mubelotix/admarus
      weight: 30
    - identifier: admarus
      name: Admarus
      url: https://admarus.net
      weight: 40

markup:
  goldmark:
    renderer:
      unsafe: true
